# Generated by Django 3.2.6 on 2021-09-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_autor_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor_id',
        ),
        migrations.AddField(
            model_name='libro',
            name='autor_id',
            field=models.ManyToManyField(to='libro.Autor'),
        ),
    ]
